DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS listaDeTarefas;
DROP TABLE IF EXISTS tarefas;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE listaDeTarefas (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    Descricao TEXT,
    FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE Tarefas (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Descricao TEXT NOT NULL,
    Status TEXT NOT NULL,
    ListaID INTEGER NOT NULL,
    FOREIGN KEY (ListaID) REFERENCES listaDeTarefas(ID)
);